### ISSUE TITLE
Categories - Deselecting Hide Category icons checkbox and saving shows black column under Icon.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#499] opened 2022-12-18 18:27 UTC
WordPress 6.1.1.
Twenty Twenty Three
My calendar is the only plugin active.
Brave browser

**Describe the bug**
Going to Categories. Deselecting (unchecking) Hide Category icons and selecting "Hide category colors" or "Title text color".
Click to Save Settings.
A black column under Icon column heading is seen.

![Screenshot 2022-12-18 at 13 20 47](https://user-images.githubusercontent.com/5323259/208313114-eab9df78-6c3f-4b1b-b576-b8638d77d723.jpg)

Selecting "title background color" I see this (which visually looks correct).
![Screenshot 2022-12-18 at 13 20 14](https://user-images.githubusercontent.com/5323259/208313185-f54e46c3-33a4-4033-8a65-88fa466877ee.jpg)

--

![Screenshot 2022-12-18 at 13 28 51](https://user-images.githubusercontent.com/5323259/208313308-76f5287a-e917-43ed-a301-753832bb3bc9.jpg)

**Comment by paaljoachim** [comment] 2022-12-18 18:32
I added another category this happened to show a white square.
I also added another category that showed a black square like most of the other categories.

![Screenshot 2022-12-18 at 13 31 00](https://user-images.githubusercontent.com/5323259/208313432-0a371a76-d2b4-438b-87c0-230c190df2e3.jpg)

**Comment by joedolson** [comment] 2022-12-18 18:35
This is the same root cause as #496. Closing.

**Comment by paaljoachim** [comment] 2022-12-19 01:03
Icon list is now back in place.
The Category list looks like this:

Summer. I added a Sun icon and yellow color. Black background.
Fall I added a dark green color.
Winter I did not add icon or color. Seen as black
Spring I did not add icon or color. Seen as black.

![Screenshot 2022-12-18 at 20 02 08](https://user-images.githubusercontent.com/5323259/208329332-bd9349b4-853e-4b2e-b7d8-714d289dc771.jpg)

**Comment by joedolson** [comment] 2022-12-19 01:30
Seems fine to me. There is no icon; so nothing is shown. Unclear on the problem.

**Comment by paaljoachim** [comment] 2022-12-19 04:19
I do not understand why there is a black background in some places and white in other places. I would think that the background should in general be white. As white is just as a standard background color.

**Comment by joedolson** [comment] 2022-12-20 19:07
It's the color that provides the best contrast against the selected category color. So it's the color that would be visible in the admin whenever colors are being opposed.

**Comment by joedolson** [comment] 2022-12-21 20:00
This is changed in https://github.com/joedolson/my-calendar/commit/03ec39dfe49a1d448297e2811f6de09e2d782c43#diff-d55b2099105cecc1c34b7a99d934cc8fa5f7c13921210a116995cff01ce25c3f. If no icon is selected, treated as empty value rather than half completed value.

**Closed by joedolson** 2022-12-21 20:00 UTC

**Comment by paaljoachim** [comment] 2022-12-22 04:15
Oooo Yes this looks a lot better!

![Screenshot 2022-12-21 at 23 13 34](https://user-images.githubusercontent.com/5323259/209054393-d34d0723-fac6-4bde-b028-519e0cc58da0.jpg)

Of course it can be fine tuned so all the boxes are the same height, but that is something for perhaps some other time.
