### ISSUE TITLE
My Calendar left WP menu (another) adjustment

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#92] opened 2021-07-11 22:04 UTC
I have noticed over and over again that I often click the first link in the drop down "Add Event" but I actually meant to click Events.

<img width="158" alt="Screen Shot 2021-07-11 at 23 54 51" src="https://user-images.githubusercontent.com/5323259/125211018-94449000-e2a3-11eb-83e6-4aacf6d57048.png">

I looked at the Pages and Posts submenus and noticed this UI pattern:

Pages
- All Pages
- New Page

Posts
- All Posts
- New Post
- Categories
- Tags

I suggest that we make these changes. New order.

Events
Add Event
(Remove: "Add New Location")
Locations
Categories
Style Editor
Shortcodes
Script Manager
Template Editor
Settings
Help

![My-Calendar-WP-left-side-sub-menu](https://user-images.githubusercontent.com/5323259/125211145-a8d55800-e2a4-11eb-80e8-0fbc0972a2ac.jpg)

**Comment by joedolson** [comment] 2021-07-11 22:55
Making the Events / Add Event match the usual WordPress order makes sense. I think I'll also change the text to 'New Event' instead of 'Add Event', for the same reason.

I can't remove 'Add New Location' until I've combined all location management into a single screen - otherwise, the My Calendar menu will close when a user goes to add a location, so that will have to wait, for now.

**Comment by joedolson** [comment] 2021-07-11 23:05
Ugh. OK, it's not that simple. If I'd made the manage events page the top-level calendar page at least 7 years ago, it would be very doable; but now it's a problem. The first child item in a sub-menu is always a duplicate of the top level page. You can re-name it, but it's always the same link as the menu item. So if I move Add Event anywhere other than the first position, I just end up with both links. 

But changing the top level link will have some back-compat complications with My Calendar extensions that would be ugly to clean up.

**Comment by paaljoachim** [comment] 2021-07-16 11:48
It sounds like we should just accept how it is for the time being, and move on to other things..

**Closed** 2021-07-30 01:29 UTC
