### ISSUE TITLE
Handling for featured images in block themes

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#197] opened 2021-09-09 12:43 UTC
I added a featured image to an event. In the content area I added "Here is some event information."

![Screenshot 2021-09-09 at 14 40 48](https://user-images.githubusercontent.com/5323259/132687477-59590d7c-2fee-42e7-9088-61f604bf0351.jpg)

Checked the frontend. (Popup event view)
![Screenshot 2021-09-09 at 14 41 31](https://user-images.githubusercontent.com/5323259/132687565-7dca7832-b3f0-4a54-8506-f44fa58cff4d.jpg)

Clicking Read more. Going to Event.

33% zoom mode.
![Screenshot 2021-09-09 at 14 42 29](https://user-images.githubusercontent.com/5323259/132687755-6a63ea5c-191c-44d1-b6c3-8f27bc0b3fcd.jpg)

**Comment by joedolson** [comment] 2021-09-09 15:20
This is a tough one. That's because the image is called in both the theme template & in the My Calendar template. I can't easily fix this, since I don't actually have any way to know whether or not the theme calls the featured image.

**Comment by paaljoachim** [comment] 2021-09-09 19:09
What would be a nice work around for this? As I have a feeling there might be a simple work around.

**Comment by joedolson** [comment] 2021-09-10 14:55
I think the closest I could manage would be logic that doesn't show the featured image My Calendar template tag if the current view is a singular template that isn't specific to the My Calendar post type and is a theme that supports featured images.

If somebody has added a custom My Calendar template, then I should assume that they want exactly what they're showing. 

I'd definitely need a filter that would override that logic, since this wouldn't catch every case, but it might be feasible.

**Comment by joedolson** [comment] 2021-09-10 23:34
https://github.com/joedolson/my-calendar/commit/68dd410a79b79872c4663767d572680f6e0055e1 is targeted at addressing this. Will require some testing in a variety of themes and configurations, I think.

**Comment by paaljoachim** [comment] 2021-10-10 13:23
I went ahead and made a new label and called it "testing".
As we will need to circle back to this issue later on.

**Comment by paaljoachim** [comment] 2021-12-04 22:36
Testing environment:
Chrome
Local test site in Desktop Server.
WordPress 5.8.2
My Calendar - newest version 4 December.

Default Settings -> Display.
Single Event - Featured Image not checked. 
Main View (Popup or List) - Featured Image not checked. 
Mini - Featured Image checked.


### Testing following top popular themes

**Astra** 
Main View: Did not show the featured image.
Single Event: Showed the featured image above the event title. 
Mini: Showed the featured image in the popup.

**Ashe** - (A nice inspirational theme.)
Main View: Did not show the featured image.
Single Event: The featured image was also seen on the frontend.
Mini: Showed the featured image in the popup, but did not include the X, and there was an error here.
Not able to get to the Single Event as the Read More text link was not seen in the popup. I "cheated" and through the backend went to Events and selected to view an event. 

**Blocksy**
Main View: Did not show the featured image.
Single Event: Did not show the featured image.
Mini: Showed the featured image in the popup.

**Colobri** 
Main View: Did not show the featured image. (Got stuck showed a grey overlay nothing was clickable and I had to refresh the page.)
Single event: (went to backend, events and clicked to view an event on the frontend) Showed the featured image. 
Mini: Showed the featured image in a very large popup.

**Cormorant**
Main View: Did not show the featured image. 
Single event: Showed the featured image below the event title. (CSS table dots were seen.)
Mini: Showed the featured image in the popup.

**GeneratePress**
Main View: Did not show the featured image. 
Single event: Showed the featured image above the event title. 
Mini: Showed the featured image in the popup.

**Go**
Main View: Did not show the featured image. (Event not scrollable and information was cut. Not able to enter single event.)
Single event: (I had to go to the backend. Events and view the event on the frontend.) Featured image seen full width above event title.
Mini: Showed the featured image in the popup. (event not scrollable)

**Hestia** 
Main View: Did not show the featured image. 
Single event: showed the featured image full width behind the event title.
Mini: Showed the featured image in the popup.

**Kadence**
Main View: Did not show the featured image. 
Single Event: Did not show the featured image.
Mini: Showed the featured image in a very large popup.

**Neve**
Main View: Did not show the featured image. 
Single View: (Not able to enter as popup went below browser window. Went to the backend. Events and view event on frontend.) Showed the featured image below the event title. 
Mini: Showed the featured image in a large popup. (Footer copyright notice showed across the featured image)

**OceanWP**
Main View: Did not show the featured image. 
Single event: Showed the featured image above the event title. 
Mini: Showed the featured image in the popup.

**TT1 Blocks**
Main View: Did not show the featured image. 
Single Event: Did not show the featured image.
Mini: Showed the featured image in the popup.

**Twenty Eleven**
Main View: Did not show the featured image. 
Single event: Showed the featured image above the event title. 
Mini: Showed the featured image in the popup.

**Twenty Twelve**
Main View: Did not show the featured image. (barely showed the Read more text link.)
Single event: Showed the featured image above the event title. 
Mini: Showed the featured image in the popup. (information cut off -  sidebar widget was removed.)

**Twenty Fourteen**
Main View: Did not show the featured image. 
Single event: Showed the featured image above the event title. 
Mini: Showed the featured image in the popup. (Proudly powered by WordPress footer bar crosses over popup.)

**Twenty Fifteen**
Main View: Did not show the featured image. 
Single event: Showed the featured image above the event title. 
Mini: Showed the featured image in the popup. 


**Twenty Sixteen**
Main View: Did not show the featured image. (List/Grid - month-week-day was cutoff from the main calendar.)
Single event: Showed the featured image below the event title. 
Mini: Showed the featured image in the popup. 


**Twenty Seventeen**
Main View: Did not show the featured image. 
Single event: Showed the featured image above the event title. 
Mini: Showed the featured image in the popup.

**Twenty Nineteen**
Main View: Did not show the featured image. 
Single event: Showed the featured image full width behind header and the event title. 
Mini: Showed the featured image in the popup.

**Twenty Twenty**
Main View Grid: Did not show the featured image. (Event not scrollable and was cut off. Could not access Single Event. Doing so through backend or through List view.)
List I was able to see the information and access the Read more text link.
Single event: Showed the featured image below the event title. 
Mini: Showed the featured image in the popup. (event not scrollable and it was cut off.)


**Twenty Twenty-One**
Main View: Did not show the featured image. 
Single event: Showed the featured image below the event title. 
Mini: Showed the featured image in the popup.


**Twenty Twenty-Two** Same as Twenty Twenty-One
Main View: Did not show the featured image. 
Single event: Showed the featured image below the event title. 
Mini: Showed the featured image in the popup.

**Comment by joedolson** [comment] 2021-12-05 18:35
On superficial read through, this seems pretty much as expected. The display problems in Twenty Twenty & Ashe aren't anything I can do something about - they're using `overflow:hidden`, which is almost always a totally unnecessary and problematic choice in theme design. But there's no practical way to fix it without addressing the specific scenario.

Showing the featured image means "showing the featured image in the My Calendar template", so it's not expected to do anything about the theme template. 

However, it doesn't seem like you ran a test with the featured image enabled in My Calendar, which is where the problems are more likely to be - the change I made is to attempt to prevent the featured image from appearing twice when featured images are turned on. 

I'll leave this open for now, but there's nothing in this round of testing that I'm going to address.

**Comment by paaljoachim** [comment] 2021-12-05 20:03
What I did was first check without Featured Image checked in the Single Event and Main View. I went through to see how My Calendar functioned in various themes. Many themes were able to show Main View (Grid and List), Single Event and Mini Calendar pretty well. Of course some themes used code that did not make My Calendar function as well as it should. I can always e-mail some of these theme creators and let them know about this.

I checked a few themes where I checked the featured image checkbox for Single Event and Main View. I also edited the above check list I made and checked a bunch more themes to see if they had double up of featured images. I have not seen any double up on the featured image.

One problem I came across was that TT1 and Twenty Twenty Two show very large featured images in the single event screen. It seems these will show the featured image at the largest size the image is uploaded as.


![Screenshot 2021-12-05 at 21 00 54](https://user-images.githubusercontent.com/5323259/144761856-2919a2c3-3683-4048-b404-a277848fd5dd.jpg)

**Comment by joedolson** [comment] 2021-12-05 20:35
What's the context there? If it's a single event view in TT1, I would expect the theme's featured image block to be shown, not the event image; is there something else going on there?

**Comment by paaljoachim** [comment] 2021-12-05 21:02
Retesting TT1 and Twenty Twenty Two. (Featured Image is checked for all views. Both views show these views the same way.)

Popup view.
Shows the featured image, and the content image. Content image stretches far outside the popup.

List view. 
Featured image is seen. Content image stretches further than the view port so one needs to scroll. Similar to Popup view.

Single Event view. Featured image is not seen. Here again the content image stretches far  o the right so one needs to scroll.

**Comment by joedolson** [comment] 2021-12-05 21:18
Are you sure you're not testing TT1 Blocks, rather than TT1?

**Comment by joedolson** [comment] 2021-12-05 21:18
Whoops. Didn't mean to close.

**Comment by joedolson** [comment] 2021-12-05 21:22
Although I don't get that with TT1 Blocks, either. I can't figure out how to reproduce this.

**Comment by paaljoachim** [comment] 2021-12-05 21:46
I am using TT1 Blocks. (Forgot to say the Blocks part.)

Chrome
Desktop Server local site.

Single Event view in TT1 Blocks. A huge horizontal scrollbar.
![Huge content image with horizontal scrollbars](https://user-images.githubusercontent.com/5323259/144765058-0fd8f64a-b32c-40b6-ba86-c741b4393777.jpg)

Zoomed out view.
![Huge-content-image-TT1](https://user-images.githubusercontent.com/5323259/144765025-352b890d-5354-4453-8df0-fdf00d9064d7.jpg)

**Comment by joedolson** [comment] 2021-12-05 21:51
So, block themes are a bit of a mystery for support. I assume that block themes don't have `current_theme_supports( 'post-thumbnails' )`, because that block would be added on demand or something? How does that work? That would explain why the my calendar image is visible and not the theme featured image. The image width is probably also a block thing with max-width.

I haven't been able to cope with block themes or full site editing, so I really don't have a lot of familiarity with what I might have to do extra in order to support those themes.

**Comment by paaljoachim** [comment] 2021-12-07 13:20
I received a response from Kjell in the Twenty Twenty Two issue: https://github.com/WordPress/twentytwentytwo/issues/273

> "...I assume that block themes don't have current_theme_supports( 'post-thumbnails' ), because that block would be added on demand or something? How does that work? "

It's possible. That is it's supposed to be added by default for Block Themes but in the Beta it is currently not happening.

**Comment by paaljoachim** [comment] 2021-12-07 16:00
Single Event screen:
Twenty Twenty-One is showing the featured image.
TT1 Blocks is not showing the featured image.
TT2 shows the featured image.

![Screenshot 2021-12-07 at 16 59 41](https://user-images.githubusercontent.com/5323259/145063224-c08a46b9-4a60-402d-8a68-f02586792c0a.jpg)

**Comment by joedolson** [comment] 2021-12-08 17:45
It seems to me like there are complicating factors with block themes. I think that block themes are still too beta for it to really be worthwhile to try and resolve this now. Going to rename this and milestone for 3.4, although from a practical standpoint the milestone will really be "when block themes are mature enough to debug for"

**Comment by paaljoachim** [comment] 2021-12-08 20:58
Sounds like a good idea!

Btw Twenty Twenty Two does show the featured image, so that is a good sign.
For whatever reason TT1 blocks does not show the featured image.

In a few months time I can retest a few block themes to see how it is working.

**Comment by joedolson** [comment] 2022-12-22 00:36
Reading through this, almost all of the outstanding problems were with TT1 Blocks. I know that was basically experimental, hasn't been maintained, and depends on a lot of beta things that have been changed....so I think it makes sense to close this. There may be relevant issues, but I think those may be better handled on a theme-by-theme basis if they come up.

**Closed by joedolson** 2022-12-22 00:36 UTC
Labels: testing

**Comment by paaljoachim** [comment] 2022-12-22 05:19
I am doing some explorations with focus on Twenty Twenty Three (FSE theme) which I will bring into a new issue.
